blank_issues_enabled: false
contact_links:
  - name: Suporte e Dúvidas
    url: https://github.com/dexcarva/AlbionInsight/discussions
    about: Por favor, use a seção de Discussões para perguntas e suporte.
